# 1
Code to create a dataframe from a dictionary and display it

In [ ]:
import pandas as pd

dict = {
    'Name' : ["B","A","C"],
    'Enrollment' : [20, 10, 30],
    'SPI' : [9.10, 9.00, 9.20]
}

df = pd.DataFrame(dict, columns = ['Name', 'Enrollment', 'SPI'])
print(df)

# 2 
Code to sort the DataFrame first by 'name' in ascending order

In [ ]:
df = df.sort_values(by = ['Name'])
print(df)

# 3
Code to delete the one specific column from the DataFrame

In [ ]:
del df["SPI"]
print(df)

# 4
Code to write a DataFrame to CSV file using tab separator

In [ ]:
print("Original DataFrame : \n",df)

df.to_csv("First.csv", sep = '\t')
new_df = pd.read_csv('First.csv')

print("Data from First.csv : \n",new_df)